FROM tensorflow/tensorflow:latest-devel-py3

RUN pip install gunicorn
RUN pip install picasso-viz

ENV EXAMPLE_DIR /usr/local/lib/python3.5/dist-packages/picasso/examples/tensorflow

ENV PICASSO_SETTINGS $EXAMPLE_DIR/config.py

EXPOSE 80

ENTRYPOINT gunicorn picasso:app --bind=0.0.0.0:80
